stages:
    - build
    - deploy
build:
    variables:
        GIT_STRATEGY: clone
    stage: build
    script:
        - docker build -t fe-viettin-1:lastest .
    tags:
        - viettin-runner
deploy:
    variables:
        GIT_STRATEGY: none
    stage: deploy
    script:
        - docker rm -f viettin-fe-1
        - docker run --name viettin-fe-1 -dp 4242:4242 fe-viettin-1:lastest
    tags:
        - viettin-runner

