stages:
    - build
    - deploy
build:
    variables:
        GIT_STRATEGY: clone
    stage: build
    script:
        - whoami
        - pwd
        - ls
    tags:
        - viettin-runner
# deploy:
#     variables:
#         GIT_STRATEGY: none
#     stage: deploy
#     script:
#         - docker run --name viettin-fe-1 -dp 4242:4242 viettin-fe-1:lastest
#     tags:
#         - viettin-runner

